version: '3.9'

services:
  marketplaceassistantbot:
    image: ghcr.io/pavluninvladimir/marketplace-assistant-bot:latest
    env_file:
      - stack.env
    networks:
      - marketplaceassistantbot
    ports:
      - "8080:8080"

networks:
  marketplaceassistantbot:
    name: tradinghousestar
