// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

// 333333
type Bot struct {
	// ID dhjdsgkdfhgdhgjkhdgjkhdgk
	ID string `json:"id"`
	// ID dhjdsgkdfhgdhgjkhdgjkhdgk
	Name string `json:"Name"`
}
