name: GoBuild

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TOKEN_TELEGRAM_BOT: 2121211

    steps:
    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.5'
    - run: go version

    - name: Get dependencies
      run: go mod download

    - name: Build
      run: go build -v .

#    - name: Test
#      run: go test -v ./...

    - name: Check for errors
      run: |
        if [ ${{ job.status }} != 'success' ]; then
          echo "Build or test failed, preventing merge"
          exit 1
        fi
      if: always()

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64 -t ghcr.io/pavluninvladimir/marketplace-assistant-bot:latest --output type=registry .

      - name: Logout from Docker registry
        run: docker logout ghcr.io