name: GoBuild

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TOKEN_TELEGRAM_BOT: 2121211

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: '1.21.5'
    - run: go version

    - name: Get dependencies
      run: go mod download

    - name: Build
      run: go build -v .

#    - name: Test
#      run: go test -v ./...

    - name: Check for errors
      run: |
        if [ ${{ job.status }} != 'success' ]; then
          echo "Build or test failed, preventing merge"
          exit 1
        fi
      if: always()