name: Go Build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TOKEN_TELEGRAM_BOT: 212121

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'

    - name: Get dependencies
      run: go mod download

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v ./...
