name: Go app with Autocannon load test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TOKEN_TELEGRAM_BOT: 2121211

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.3'

      - name: Build Go App
        run: go build -o app

      - name: Start Go App
        run: ./app &

      - name: Wait for App to Start
        run: sleep 5s

      - name: Run Autocannon load test
        id: autocannon
        run: |
          npm install autocannon && node autocannon/index.js
        env:
          GITHUB_OUTPUT: ${{ steps.server.outputs.pid }}

      - name: Stop Go App
        run: pkill app