name: Go app with Autocannon load test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TOKEN_TELEGRAM_BOT: 2121211

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.3'

      - name: Build Go App
        run: go build -o app

      - name: Start Go App
        run: ./app &

      - name: Wait for App to Start
        run: sleep 5s

      - name: Run Autocannon Load Test
        run:  |
              set -e
              npx autocannon -c 10 -d 5 -p 10 http://localhost:8181 | tee output.txt
              export AVG=$(grep 'Avg' output.txt | awk '{print $2}' | tr -d ',')
              if (( $(echo "$AVG < 10000" | bc -l) )); then
                echo "Average response time is less than 10000ms: $AVG ms"
                exit 1
              else
                echo "Average response time is greater than or equal to 10000ms: $AVG ms"
              fi
        env:
          GITHUB_OUTPUT: ${{ steps.server.outputs.pid }}

      - name: Stop Go App
        run: pkill app